Client Write Operation
CMPE275-Distributed-Systems/CMPE_275_Final pull request #4
Opened 2024-12-11 03:00 UTC by adityarao97

2024-12-11 05:52 UTC, nsalazar0429 commented
Client should not be a route. Instead, it should be a stand alone entity that only handles its own files. Ex: JAVA Application, Web Site, etc

In this case, it can be a JAVA app since we don't need GUI

2024-12-15 10:15 UTC, nsalazar0429 commented on .idea/uiDesigner.xml
> +<project version="4">
File should not be commited

2024-12-15 10:17 UTC, nsalazar0429 commented on chunkmaster/src/main/java/com/example/chunkmaster/ChunkMasterController.java
> +    public record Chunk(String id, String content) {}
Let's change id to use `ChunkMetadata` that contains id and fileName

2024-12-15 10:19 UTC, nsalazar0429 commented on client/src/main/java/com/example/client/entity/Chunk.java
> +}
Let's use the same model

2024-12-15 10:19 UTC, nsalazar0429 commented on client/src/main/java/com/example/client/service/ClientProcessor.java
> +        //converting byteArray back to file format and saving it
remove commented code

2024-12-15 10:19 UTC, nsalazar0429 commented on client/src/main/java/com/example/client/service/ClientService.java
> +//        }
commented code

2024-12-15 10:20 UTC, nsalazar0429 commented on files/mainCheck/001e26c7-a83a-4533-b356-a59483be9dd8.txt
> +o�/��{�/����Vց�[)^~n�2e��%��u�M����|�%A�|�+� Wv�0��ҩ���������>p�l�����x�΍��H��Z0�$���0�<�S>n���4r�`/{�{|MK��K��\YY�{)jO툕}��U�M'�=#b7Z��f�L�Ni���6Z�L�Yw2HZV������\|�����/񮇷�/�i{ݜ��#7
This should not be commited , right ?

2024-12-15 10:20 UTC, nsalazar0429 requested changes
Let's not merge unneccesary files

2024-12-16 04:34 UTC, Phuoc-L submitted a review, later dismissed
looks good

2024-12-16 04:34 UTC, karandesai-sjsu approved these changes
Good

2024-12-16 04:47 UTC, nsalazar0429 approved these changes

2024-12-16 04:47 UTC, Phuoc-L approved these changes
good

2024-12-16 04:47 UTC, karandesai-sjsu approved these changes
done

2024-12-16 04:49 UTC, merged